name: Build
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    uses: refinedmods/refinedarchitect/.github/workflows/build.yml@v0.21.0
    with:
      mutation-testing: false
      sonarqube: true
    secrets: inherit
